# Generated by Django 3.2.5 on 2022-04-14 14:09

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_userinfo_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='articles',
            name='comment_nums',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='articles',
            name='info',
            field=models.CharField(default='', max_length=100, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='images/users/default.png', upload_to='images/users'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='留言内容'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=500, verbose_name='评论详情')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.articles', verbose_name='留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
            },
        ),
    ]
