# Generated by Django 3.2.5 on 2022-04-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20220414_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
